const enc = new TextEncoder();
const b64u = b => btoa(String.fromCharCode(...new Uint8Array(b))).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");
const unb64u = s => Uint8Array.from(atob(s.replaceAll("-","+").replaceAll("_","/")+"=="),c=>c.charCodeAt(0));
async function hashPassword(p,salt){const key=await crypto.subtle.importKey("raw",enc.encode(p),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(salt),iterations:120000,hash:"SHA-256"},key,256);return b64u(bits)}
function tokenFor(u){return b64u(enc.encode(JSON.stringify({id:u.id,username:u.username,iat:Date.now()})))}
function json(o,s=200){return new Response(JSON.stringify(o),{status:s,headers:{"content-type":"application/json;charset=utf-8","cache-control":"no-store"}})}
async function body(req){try{return await req.json()}catch{return {}}}
async function userFrom(req,env){const h=req.headers.get("authorization")||"";if(h.startsWith("Bearer ")){try{const p=JSON.parse(new TextDecoder().decode(unb64u(h.slice(7))));return await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(p.id).first()}catch{}}const n=req.headers.get("x-user-name");if(n){return await env.DB.prepare("SELECT * FROM users WHERE username=?").bind(decodeURIComponent(n)).first()}return null}
function publicUser(u){if(!u)return null;return {id:u.id,username:u.username,points:u.points,level:u.level,xp:u.xp,body_size:u.body_size,evolution:u.evolution,wins:u.wins,losses:u.losses,energy:u.energy??100,fullness:u.fullness??100,title:["아기토끼","성장토끼","반짝토끼","왕관토끼","보석토끼","별빛토끼"][Math.min(u.evolution,5)]}}
async function ensureColumns(env){/* schema.sql already includes these in v1 */ }
async function api(req,env,url){
 const path=url.pathname;
 if(req.method==="POST"&&path==="/api/register"){const b=await body(req);const username=String(b.username||"").trim();const password=String(b.password||"");if(username.length<2||username.length>20)return json({error:"닉네임은 2~20자입니다."},400);if(password.length<4)return json({error:"비밀번호는 4자 이상입니다."},400);const old=await env.DB.prepare("SELECT id FROM users WHERE username=?").bind(username).first();if(old)return json({error:"이미 사용 중인 닉네임입니다."},409);const salt=crypto.randomUUID();const ph=await hashPassword(password,salt);const r=await env.DB.prepare("INSERT INTO users(username,password_hash,points,level,xp,body_size,evolution,wins,losses,energy,fullness,password_salt) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(username,ph,10000,1,0,0,0,0,0,100,100,salt).run();const u=await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(r.meta.last_row_id).first();return json({user:publicUser(u),token:tokenFor(u)})}
 if(req.method==="POST"&&path==="/api/login"){const b=await body(req);const u=await env.DB.prepare("SELECT * FROM users WHERE username=?").bind(String(b.username||"")).first();if(!u)return json({error:"닉네임 또는 비밀번호가 틀렸습니다."},401);const ph=await hashPassword(String(b.password||""),u.password_salt||"legacy");if(ph!==u.password_hash)return json({error:"닉네임 또는 비밀번호가 틀렸습니다."},401);return json({user:publicUser(u),token:tokenFor(u)})}
 const u=await userFrom(req,env);if(!u)return json({error:"로그인이 필요합니다."},401);
 if(path==="/api/me")return json({user:publicUser(u)});
 if(path==="/api/action"&&req.method==="POST"){const b=await body(req);let p=u.points,e=u.energy??100,f=u.fullness??100,x=u.xp,l=u.level,msg="";if(b.action==="work"){p+=500;e=Math.max(0,e-5);f=Math.max(0,f-4);x+=25;msg="일해서 500P와 XP를 얻었어요! 💼"}if(b.action==="cook"){f=Math.min(100,f+20);e=Math.max(0,e-3);x+=15;msg="맛있는 요리 완료! 🍳"}if(b.action==="rest"){e=Math.min(100,e+30);f=Math.max(0,f-2);x+=10;msg="푹 쉬었어요! 🛋️"}while(x>=100+(l-1)*80){x-=100+(l-1)*80;l++;if(l%5===0){await env.DB.prepare("UPDATE users SET evolution=evolution+1 WHERE id=?").bind(u.id).run();msg+="\n🎉 하니가 진화했어요!"}}await env.DB.prepare("UPDATE users SET points=?,energy=?,fullness=?,xp=?,level=? WHERE id=?").bind(p,e,f,x,l,u.id).run();const nu=await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(u.id).first();return json({message:msg,user:publicUser(nu)})}
 if(path==="/api/ranking"){const [p,l,w]=await Promise.all([env.DB.prepare("SELECT username,points FROM users ORDER BY points DESC LIMIT 5").all(),env.DB.prepare("SELECT username,level,xp FROM users ORDER BY level DESC,xp DESC LIMIT 5").all(),env.DB.prepare("SELECT username,wins FROM users ORDER BY wins DESC LIMIT 5").all()]);return json({rankings:{points:p.results,level:l.results,games:w.results}})}
 if(path==="/api/rooms"&&req.method==="GET"){const game=url.searchParams.get("game");const q=game?env.DB.prepare("SELECT room_code,game,stake,status,created_at FROM rooms WHERE game=? AND status='waiting' ORDER BY created_at DESC LIMIT 30").bind(game):env.DB.prepare("SELECT room_code,game,stake,status,created_at FROM rooms WHERE status='waiting' ORDER BY created_at DESC LIMIT 30");return json({rooms:(await q.all()).results})}
 if(path==="/api/rooms"&&req.method==="POST"){const b=await body(req),game=String(b.game||"omok"),stake=Math.max(0,Number(b.stake||0));if(!["omok","tetris","shisen"].includes(game))return json({error:"지원하지 않는 게임입니다."},400);if(stake>u.points)return json({error:"포인트가 부족합니다."},400);const code=Math.random().toString(36).slice(2,7).toUpperCase();await env.DB.prepare("INSERT INTO rooms(room_code,game,host_id,stake,status) VALUES(?,?,?,?,?)").bind(code,game,u.id,stake,"waiting").run();return json({room:{room_code:code,game,stake,status:"waiting"}})}
 const m=path.match(/^\/api\/rooms\/([^/]+)\/join$/);if(m&&req.method==="POST"){const code=m[1];const r=await env.DB.prepare("SELECT * FROM rooms WHERE room_code=?").bind(code).first();if(!r)return json({error:"방이 없습니다."},404);if(r.guest_id)return json({error:"이미 가득 찬 방입니다."},409);await env.DB.prepare("UPDATE rooms SET guest_id=?,status='ready' WHERE room_code=?").bind(u.id,code).run();return json({ok:true})}
 return json({error:"API를 찾을 수 없습니다."},404)
}
export default {async fetch(req,env){const url=new URL(req.url);if(url.pathname.startsWith("/api/"))return api(req,env,url);return env.ASSETS.fetch(req)}}
